lib/components/molecules/reference_info_tile.dart
lib/constants.dart
lib/main.dart

Now you can go to each version release notes from the app
closes #2

Added link to release notes

---

.github/workflows/release.yml
lib/app_shell.dart
lib/components/molecules/update_card.dart
lib/constants.dart
lib/main.dart
lib/utils/manage_updates.dart
lib/version.dart
pubspec.lock
pubspec.yaml

Still needs to be added to Settings but will be done in a separate PR

Add checking for update function

---

lib/components/molecules/github_repo_info.dart
lib/components/molecules/project_version_select.dart
lib/providers/releases.provider.dart
lib/screens/packages_screen.dart

Small change that adds actions for the Github stats on Packages (Stargazers, Network, Issues) as well as adding a text widget on error for packages to give some more info

Packages Screen Tweaks

---

lib/components/molecules/empty_data_set/empty_packages.dart
lib/components/molecules/empty_data_set/empty_projects.dart
lib/providers/navigation_provider.dart
lib/screens/settings_scenes/settings_section_projects.dart

Settings fixes on windows

---

lib/components/atoms/screen.dart
lib/components/atoms/top_app_bar.dart
lib/components/molecules/channel_showcase.dart
lib/screens/releases_screen.dart
lib/screens/settings_scenes/settings_section_general.dart
lib/utils/dependencies.dart
pubspec.lock
pubspec.yaml

Layout fixes

---

windows/runner/main.cpp

Added conditional for process

---

lib/components/molecules/package_score_display.dart
lib/providers/projects_provider.dart

Fix if package score is pending

---

lib/providers/flutter_releases.provider.dart
lib/providers/fvm_cache.provider.dart
lib/screens/settings_scenes/settings_section_flutter.dart
lib/services/flutter_config_service.dart

UI to display global not set

---

INSTALLING.md
README.md
lib/components/atoms/empty_data_set.dart
lib/main.dart
lib/screens/error_db_screen.dart
lib/services/settings_service.dart

If more than one instance of sidekick is launched then the new one will close to prevent the database (hive) from being accessed by multiple instances.
background icons with no color are now visible in light mode

Small UI/UX fixes

---

lib/src/theme.dart

Fix issue when platform and theme brightness does not match

---

lib/main.dart
lib/src/modules/common/utils/migrateFiles.dart
macos/Flutter/GeneratedPluginRegistrant.swift
macos/Podfile.lock
macos/Runner.xcodeproj/project.pbxproj
pubspec.lock
pubspec.yaml

This would be a breaking change as all user settings (for sidekick) would be lost. This PR simply changes the db location to the `getApplicationSupportDirectory()` instead of the Documents folder, which should solve permission issues.
Linked PR: https://github.com/flutter/plugins/pull/3691

Fix #100 (Change DB location)

---

lib/src/modules/updater/updater.utils.dart

Add linux AppImage auto update

---

.fvm/fvm_config.json
.vscode/settings.json
lib/main.dart
lib/src/components/atoms/console.dart
lib/src/components/molecules/version_install_button.dart
lib/src/components/organisms/shortcut_manager.dart
lib/src/modules/common/app_shell.dart
lib/src/modules/common/utils/indexed_transition_switcher.dart
lib/src/modules/fvm/fvm.provider.dart
lib/src/modules/fvm/fvm.screen.dart
lib/src/modules/releases/releases.provider.dart
lib/src/modules/releases/releases.screen.dart
lib/src/modules/settings/settings.provider.dart
pubspec.lock
pubspec.yaml

Memo sorting functions, modified page switcher

Performance improvements

---

lib/src/components/atoms/typography.dart
lib/src/modules/sandbox/components/sandbox_terminal.dart
lib/src/modules/sandbox/sandbox.provider.dart
lib/src/modules/sandbox/sandbox.screen.dart

Make playground text selectable

---

lib/src/modules/fvm/dialogs/fvm_global_dialog.dart

feat fvm_global_dialog.dart add copy Flutter PATH value button

---

lib/src/modules/common/app_shell.dart
lib/src/theme.dart

Fixed transition background update after theme change

---

localizations/pl-PL/components.json
localizations/pl-PL/modules.json

Corrections and removal of Swedish values from Polish translation.

Polish translation improvements

---

macos/Podfile.lock
macos/Runner.xcodeproj/project.pbxproj
pubspec.lock
pubspec.yaml

Issue https://github.com/bitsdojo/bitsdojo_window/issues/148 seems to be resolved in the latest version

Upgrade `bitsdojo_window`

---

lib/src/modules/releases/releases.provider.dart
pubspec.lock
pubspec.yaml

Remove duplicate releases

---

.vscode/launch.json
pubspec.lock
pubspec.yaml

Fix windows

---

localizations/tr-TR/components.json
localizations/tr-TR/modules.json

yesterday before I submitted #282, I had asked some friends about what would be the accurate translation of some technical terms. This updates the said terms accordingly

fix: turkish tech terms

---

pubspec.lock
pubspec.yaml

Bump dev-deps to fix MSIX build

---

localizations/zh-CN/modules.json

Modify the Chinese language to be more suitable for Chinese people to read

docs(translation): update zh-cn translation

---

macos/Flutter/GeneratedPluginRegistrant.swift
macos/Podfile.lock
macos/Runner.xcodeproj/project.pbxproj
pubspec.lock
pubspec.yaml

#299 
1. material_floating_search_bar It has completed the work
2. It is unclear whether Sidekick will remove FVM or MSIX

chore(pubspec): update i18next open_file window_size package
